title: My form
output:
  format: issue  # PR / Issue / Commit
  file: data.csv
  branch: main
fields:
  - name: name
    label: Name
    validation:
      - type: length
        min: 1
  - name: email
    label: E-mail
    validation: email