title: My form
output:
  format: issue  # PR / Issue / Commit
  file: data.csv
  branch: main
fields:
  - name: name
    label: Name
    type: text
    validation:
      - type: length
        min: 1
  - name: email
    label: E-mail
    type: text
    validation: email
  - name: age
    label: Age
    type: number
    validation:
      - type: gt
        min: 18